apiVersion: v1
kind: Service
metadata:
  name: python-hello-world-service
spec:
  type: NodePort
  ports:
    - port: 8000 # Port your application listens on inside the container
      targetPort: 8000 # Port your application listens on inside the container
      nodePort: 30000 # Choose an available port or leave it empty for automatic assignment
  selector:
    app: hello-world-app # Match this label with your deployment's selector
